if defined NAME
   script_name  = $(NAME)
else
   script_name  = analyzer
endif
executable   = analyzer.sh
arguments    = $(FILE_NAME)
universe     = vanilla
requirements = (OpSysAndVer =?= "CentOS7")
output       = out/$(script_name).$(ProcId).out
error        = out/$(script_name).$(ProcId).err
log          = log/$(script_name).$(ProcId).log
request_cpus = 1
request_memory = 80MB
+JobFlavour = "workday"
queue FILE_NAME from file_names.txt