script_name=selector

executable            = selector.sh
arguments 	      = $(NTUPLE_ID)
universe	      = vanilla
requirements          = (OpSysAndVer =?= "CentOS7")
output                = out/$(script_name).$(ProcId).$(NTUPLE_ID).out
error                 = out/$(script_name).$(ProcId).$(NTUPLE_ID).err
log                   = log/$(script_name).$(ProcId).log
RequestCpus	      = 10
+JobFlavour = "workday"
queue NTUPLE_ID from ntuple_ids.txt