initialdir=/afs/cern.ch/work/b/bfontana/TestBeamAnalysis/src/UserCode/CondorJobs/

executable = $(initialdir)sim_cmssw_producer.sh
arguments = --infile $(FILENAME) --celltype LD
universe = vanilla
requirements = (OpSysAndVer =?= "CentOS7")
output = out/$(Row).out
error = out/$(Row).err
log = log/$(Row).log
getenv = True
RequestMemory = 70MB
+JobFlavour = "espresso"

queue FILENAME matching files /eos/cms/store/group/dpg_hgcal/comm_hgcal/bfontana/spatial_res_LD_Final/SinglePhoton_parallel_LD/step3_nopu_GEN-SIM-RECO-FEVTDEBUGHLT_Final_LD/201203_105422/0000/out_*root