indir = /grid_mnt/vol_home/llr/cms/cuisset/hgcal/testbeam18/job-submission/src/TestBeamReconstruction/CondorJobs/
executable = launcher.sh
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
public_input_files = ../../../bin/slc7_amd64_gcc11/process_data_exe
arguments = --ntupleid 4 --datatype sim_proton_v46_patchMIP --showertype em --tag ntuples-v6 --w0 2.9 --dpos 1.3 --energy 200 --step selection
universe = vanilla
requirements = (OpSysAndVer =?= "CentOS7")
output = out/selection_sim_proton_v46_patchMIP_em_beamen200_ntuples-v6.4.out
error =  out/selection_sim_proton_v46_patchMIP_em_beamen200_ntuples-v6.4.err
log =    log/selection_sim_proton_v46_patchMIP_em_beamen200_ntuples-v6.4.log
getenv = True
RequestMemory = 1.3GB
+JobFlavour = "workday"
T3Queue = long
WNTag=el7
+SingularityCmd = ""
UNIX_GROUP = cms
accounting_group = $(UNIX_GROUP)
concurrency_limits_expr = strcat(T3Queue,":",RequestCpus," ",AcctGroupUser,":",RequestCpus)
+T3Queue="$(T3Queue)"
+T3Group="$(UNIX_GROUP)"
+WNTag="$(WNTag)"
+T3Submit=true
queue
